version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  telegram_bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    tty: true
    networks:
      - default
    env_file:
      - .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web

  web:
    build:
      context: ./rest_API
      dockerfile: Dockerfile
    container_name: rest_API
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - default
    env_file:
      - .env
    restart: always
    depends_on:
      - db
volumes:
  postgres_data: