version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - E:\PostgreSQL\14\data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - default
    restart: always

  telegram_bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  web:
    build:
      context: ./rest_API
      dockerfile:
        Dockerfile
    container_name: rest_API
#    volumes:
#      - .:/usr/src/rest_API
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - default
    env_file:
      - .env
    restart: always
    depends_on:
      - db




