# Generated by Django 4.0.2 on 2022-02-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='Full name')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('one_time', models.BooleanField(default=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manage.group', verbose_name='Group ID')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manage.group', verbose_name='Group ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manage.user', verbose_name='Group ID')),
            ],
            options={
                'verbose_name': 'Group User',
                'verbose_name_plural': 'Groups Users',
            },
        ),
        migrations.CreateModel(
            name='DateTimeForLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Time Start')),
                ('time_finish', models.TimeField(verbose_name='Time Finish')),
                ('repeat', models.IntegerField(verbose_name='Repeat')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manage.link', verbose_name='Link ID')),
            ],
            options={
                'verbose_name': 'Date and Time for Link',
                'verbose_name_plural': 'Date and Time for Links',
            },
        ),
    ]
